/**
 * /terms — Terms of Service.
 *
 * The page exists so the URL is live for vendor security questionnaires
 * and contract review ("link your ToS URL"). The copy is a generic
 * placeholder marked DRAFT. Before signing the first paying ISO,
 * replace this with copy generated by a legal-tech tool (Termly,
 * Iubenda, etc.) or a lawyer.
 *
 * The "DRAFT" banner is visible on every load so no one mistakes this
 * for production-ready language.
 */
import { LegalPageShell } from "../components/LegalPageShell";

export function TermsPage() {
  return (
    <LegalPageShell
      title="Terms of Service"
      lastUpdated="May 29, 2026 (DRAFT)"
    >
      <section>
        <h2>1. Acceptance of Terms</h2>
        <p>
          By accessing or using navigatr (the &ldquo;Service&rdquo;) you agree
          to be bound by these Terms of Service. If you do not agree, do not
          use the Service.
        </p>
      </section>

      <section>
        <h2>2. Description of Service</h2>
        <p>
          navigatr is a mobile-first sales platform for outside sales
          professionals in merchant services, payroll, and treasury
          management. The Service provides pipeline management, activity
          tracking, partner attribution, and related sales-enablement
          functionality.
        </p>
      </section>

      <section>
        <h2>3. Account Registration</h2>
        <p>
          You must provide accurate information when creating an account.
          You are responsible for maintaining the confidentiality of your
          account credentials and for all activity that occurs under your
          account.
        </p>
      </section>

      <section>
        <h2>4. Acceptable Use</h2>
        <p>You agree not to use the Service to:</p>
        <ul>
          <li>Violate any law or regulation</li>
          <li>Infringe any party&apos;s intellectual property rights</li>
          <li>Transmit malware or attempt to gain unauthorized access</li>
          <li>Send unsolicited bulk communications</li>
          <li>Interfere with or disrupt the Service</li>
        </ul>
      </section>

      <section>
        <h2>5. Data and Privacy</h2>
        <p>
          Your use of the Service is also governed by our{" "}
          <a href="/privacy">Privacy Policy</a>, which describes how we
          collect, use, and share information about you.
        </p>
      </section>

      <section>
        <h2>6. Intellectual Property</h2>
        <p>
          The Service and its original content, features, and functionality
          are owned by Outside Hire and are protected by international
          copyright, trademark, and other intellectual property laws.
        </p>
      </section>

      <section>
        <h2>7. Termination</h2>
        <p>
          We may suspend or terminate your access to the Service at any time
          for any reason, including violation of these Terms. You may stop
          using the Service at any time.
        </p>
      </section>

      <section>
        <h2>8. Disclaimer of Warranties</h2>
        <p>
          THE SERVICE IS PROVIDED &ldquo;AS IS&rdquo; AND &ldquo;AS
          AVAILABLE&rdquo; WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS
          OR IMPLIED.
        </p>
      </section>

      <section>
        <h2>9. Limitation of Liability</h2>
        <p>
          TO THE MAXIMUM EXTENT PERMITTED BY LAW, OUTSIDE HIRE SHALL NOT BE
          LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, OR CONSEQUENTIAL
          DAMAGES ARISING FROM YOUR USE OF THE SERVICE.
        </p>
      </section>

      <section>
        <h2>10. Changes to Terms</h2>
        <p>
          We may revise these Terms at any time. The &ldquo;Last
          updated&rdquo; date above reflects the most recent revision.
          Continued use of the Service after changes constitutes acceptance.
        </p>
      </section>

      <section>
        <h2>11. Contact</h2>
        <p>
          Questions about these Terms? Email{" "}
          <a href="mailto:privacy@getnavigatr.io">privacy@getnavigatr.io</a>.
        </p>
      </section>
    </LegalPageShell>
  );
}

export default TermsPage;
