-- 20260601000003_chain_handling.sql
--
-- Path Slice 5: chain confidence + brand attribution + show-chains-in-browse.
--   - prospects: chain_confidence / chain_brand_id / chain_brand_name (additive;
--     self-heal on TTL re-pull).
--   - exclusion_seed: brand_id + primary_type (the allowlist grows in this file).
--   - prospects_nearby: opt-in p_include_chains so Find Near Me can show + flag
--     chains while Create Path keeps excluding them.

alter table prospects
  add column chain_confidence text,   -- 'high' | 'medium' | 'low' | null
  add column chain_brand_id   text,
  add column chain_brand_name text;

alter table exclusion_seed
  add column brand_id     text,
  add column primary_type text;

-- Recreate prospects_nearby: signature gains p_include_chains + 3 returned chain
-- columns (before distance_m). Body otherwise identical to 20260601000001.
drop function if exists prospects_nearby(double precision, double precision, double precision, text, integer);

create function prospects_nearby(
  p_lat            double precision,
  p_lng            double precision,
  p_radius_m       double precision default 3000,
  p_profession     text default null,
  p_limit          integer default 30,
  p_include_chains boolean default false
)
returns table (
  id               uuid,
  place_id         text,
  name             text,
  category         text,
  address          text,
  lat              double precision,
  lng              double precision,
  phone            text,
  website          text,
  employee_count   integer,
  rating_count     integer,
  rating           double precision,
  primary_type     text,
  is_chain         boolean,
  chain_confidence text,
  chain_brand_name text,
  distance_m       double precision
)
language sql
stable
security definer
set search_path = public, extensions
as $$
  select
    p.id, p.place_id, p.name, p.category, p.address,
    p.lat, p.lng, p.phone, p.website, p.employee_count, p.rating_count, p.rating, p.primary_type,
    p.is_chain, p.chain_confidence, p.chain_brand_name,
    ST_Distance(p.location, ST_MakePoint(p_lng, p_lat)::geography) as distance_m
  from prospects p
  where p.in_profile
    and (p_include_chains or not p.is_chain)
    and ST_DWithin(p.location, ST_MakePoint(p_lng, p_lat)::geography, p_radius_m)
  order by distance_m asc
  limit greatest(1, least(coalesce(p_limit, 30), 100));
$$;

grant execute on function prospects_nearby(double precision, double precision, double precision, text, integer, boolean) to authenticated;

-- Grow exclusion_seed to the workbook chain allowlist. One row per match pattern;
-- all rows for a brand share brand_id. Existing seed rows collide on name_pattern
-- and get brand_id/primary_type/brand backfilled by the do-update.
insert into exclusion_seed (name_pattern, brand, brand_id, primary_type, scope) values
  ('walmart',                       'Walmart',              'walmart',          'hypermarket',              'national'),
  ('walmart supercenter',           'Walmart',              'walmart',          'hypermarket',              'national'),
  ('walmart neighborhood market',   'Walmart',              'walmart',          'hypermarket',              'national'),
  ('sam''s club',                   'Walmart',              'walmart',          'hypermarket',              'national'),
  ('target',                        'Target',               'target',           'department_store',         'national'),
  ('target store',                  'Target',               'target',           'department_store',         'national'),
  ('supertarget',                   'Target',               'target',           'department_store',         'national'),
  ('costco',                        'Costco',               'costco',           'warehouse_store',          'national'),
  ('costco wholesale',              'Costco',               'costco',           'warehouse_store',          'national'),
  ('home depot',                    'The Home Depot',       'home_depot',       'home_improvement_store',   'national'),
  ('the home depot',                'The Home Depot',       'home_depot',       'home_improvement_store',   'national'),
  ('lowe''s',                       'Lowe''s',              'lowes',            'home_improvement_store',   'national'),
  ('lowes',                         'Lowe''s',              'lowes',            'home_improvement_store',   'national'),
  ('lowe''s home improvement',      'Lowe''s',              'lowes',            'home_improvement_store',   'national'),
  ('best buy',                      'Best Buy',             'best_buy',         'electronics_store',        'national'),
  ('kohl''s',                       'Kohl''s',              'kohls',            'department_store',         'national'),
  ('kohls',                         'Kohl''s',              'kohls',            'department_store',         'national'),
  ('macy''s',                       'Macy''s',              'macys',            'department_store',         'national'),
  ('macys',                         'Macy''s',              'macys',            'department_store',         'national'),
  ('jcpenney',                      'JCPenney',             'jcpenney',         'department_store',         'national'),
  ('jc penney',                     'JCPenney',             'jcpenney',         'department_store',         'national'),
  ('j.c. penney',                   'JCPenney',             'jcpenney',         'department_store',         'national'),
  ('nordstrom',                     'Nordstrom',            'nordstrom',        'department_store',         'national'),
  ('nordstrom rack',                'Nordstrom',            'nordstrom',        'department_store',         'national'),
  ('ikea',                          'IKEA',                 'ikea',             'furniture_store',          'national'),
  ('dollar general',                'Dollar General',       'dollar_general',   'discount_store',           'national'),
  ('dollar tree',                   'Dollar Tree',          'dollar_tree',      'discount_store',           'national'),
  ('family dollar',                 'Dollar Tree',          'dollar_tree',      'discount_store',           'national'),
  ('five below',                    'Five Below',           'five_below',       'discount_store',           'national'),
  ('t.j. maxx',                     'TJX Companies',        'tjmaxx',           'discount_store',           'national'),
  ('tj maxx',                       'TJX Companies',        'tjmaxx',           'discount_store',           'national'),
  ('tjmaxx',                        'TJX Companies',        'tjmaxx',           'discount_store',           'national'),
  ('marshalls',                     'TJX Companies',        'tjmaxx',           'discount_store',           'national'),
  ('homegoods',                     'TJX Companies',        'tjmaxx',           'discount_store',           'national'),
  ('sierra trading',                'TJX Companies',        'tjmaxx',           'discount_store',           'national'),
  ('ross dress for less',           'Ross',                 'ross',             'discount_store',           'national'),
  ('ross stores',                   'Ross',                 'ross',             'discount_store',           'national'),
  ('kroger',                        'Kroger',               'kroger',           'supermarket',              'national'),
  ('ralphs',                        'Kroger',               'kroger',           'supermarket',              'national'),
  ('fred meyer',                    'Kroger',               'kroger',           'supermarket',              'national'),
  ('king soopers',                  'Kroger',               'kroger',           'supermarket',              'national'),
  ('smith''s',                      'Kroger',               'kroger',           'supermarket',              'national'),
  ('food 4 less',                   'Kroger',               'kroger',           'supermarket',              'national'),
  ('fry''s food',                   'Kroger',               'kroger',           'supermarket',              'national'),
  ('dillons',                       'Kroger',               'kroger',           'supermarket',              'national'),
  ('qfc',                           'Kroger',               'kroger',           'supermarket',              'national'),
  ('mariano''s',                    'Kroger',               'kroger',           'supermarket',              'national'),
  ('albertsons',                    'Albertsons',           'albertsons',       'supermarket',              'national'),
  ('safeway',                       'Albertsons',           'albertsons',       'supermarket',              'national'),
  ('vons',                          'Albertsons',           'albertsons',       'supermarket',              'national'),
  ('jewel-osco',                    'Albertsons',           'albertsons',       'supermarket',              'national'),
  ('shaw''s',                       'Albertsons',           'albertsons',       'supermarket',              'national'),
  ('acme markets',                  'Albertsons',           'albertsons',       'supermarket',              'national'),
  ('randalls',                      'Albertsons',           'albertsons',       'supermarket',              'national'),
  ('tom thumb',                     'Albertsons',           'albertsons',       'supermarket',              'national'),
  ('united supermarkets',           'Albertsons',           'albertsons',       'supermarket',              'national'),
  ('publix',                        'Publix',               'publix',           'supermarket',              'national'),
  ('publix super market',           'Publix',               'publix',           'supermarket',              'national'),
  ('whole foods',                   'Whole Foods Market',   'whole_foods',      'supermarket',              'national'),
  ('whole foods market',            'Whole Foods Market',   'whole_foods',      'supermarket',              'national'),
  ('trader joe''s',                 'Trader Joe''s',        'trader_joes',      'supermarket',              'national'),
  ('trader joes',                   'Trader Joe''s',        'trader_joes',      'supermarket',              'national'),
  ('aldi',                          'ALDI',                 'aldi',             'discount_store',           'national'),
  ('h-e-b',                         'H-E-B',                'heb',              'supermarket',              'national'),
  ('heb',                           'H-E-B',                'heb',              'supermarket',              'national'),
  ('h e b',                         'H-E-B',                'heb',              'supermarket',              'national'),
  ('wegmans',                       'Wegmans',              'wegmans',          'supermarket',              'national'),
  ('cvs',                           'CVS Pharmacy',         'cvs',              'drugstore',                'national'),
  ('cvs pharmacy',                  'CVS Pharmacy',         'cvs',              'drugstore',                'national'),
  ('cvs/pharmacy',                  'CVS Pharmacy',         'cvs',              'drugstore',                'national'),
  ('walgreens',                     'Walgreens',            'walgreens',        'drugstore',                'national'),
  ('duane reade',                   'Walgreens',            'walgreens',        'drugstore',                'national'),
  ('rite aid',                      'Rite Aid',             'rite_aid',         'drugstore',                'national'),
  ('mcdonald''s',                   'McDonald''s',          'mcdonalds',        'fast_food_restaurant',     'national'),
  ('mcdonalds',                     'McDonald''s',          'mcdonalds',        'fast_food_restaurant',     'national'),
  ('starbucks',                     'Starbucks',            'starbucks',        'coffee_shop',              'national'),
  ('starbucks reserve',             'Starbucks',            'starbucks',        'coffee_shop',              'national'),
  ('subway',                        'Subway',               'subway',           'sandwich_shop',            'national'),
  ('burger king',                   'Burger King',          'burger_king',      'fast_food_restaurant',     'national'),
  ('wendy''s',                      'Wendy''s',             'wendys',           'fast_food_restaurant',     'national'),
  ('wendys',                        'Wendy''s',             'wendys',           'fast_food_restaurant',     'national'),
  ('chick-fil-a',                   'Chick-fil-A',          'chick_fil_a',      'fast_food_restaurant',     'national'),
  ('chick fil a',                   'Chick-fil-A',          'chick_fil_a',      'fast_food_restaurant',     'national'),
  ('taco bell',                     'Taco Bell',            'taco_bell',        'fast_food_restaurant',     'national'),
  ('kfc',                           'KFC',                  'kfc',              'fast_food_restaurant',     'national'),
  ('kentucky fried chicken',        'KFC',                  'kfc',              'fast_food_restaurant',     'national'),
  ('popeyes',                       'Popeyes',              'popeyes',          'fast_food_restaurant',     'national'),
  ('popeye''s',                     'Popeyes',              'popeyes',          'fast_food_restaurant',     'national'),
  ('domino''s',                     'Domino''s',            'dominos',          'pizza_restaurant',         'national'),
  ('dominos',                       'Domino''s',            'dominos',          'pizza_restaurant',         'national'),
  ('domino''s pizza',               'Domino''s',            'dominos',          'pizza_restaurant',         'national'),
  ('pizza hut',                     'Pizza Hut',            'pizza_hut',        'pizza_restaurant',         'national'),
  ('little caesars',                'Little Caesars',       'little_caesars',   'pizza_restaurant',         'national'),
  ('papa john''s',                  'Papa John''s',         'papa_johns',       'pizza_restaurant',         'national'),
  ('papa johns',                    'Papa John''s',         'papa_johns',       'pizza_restaurant',         'national'),
  ('chipotle',                      'Chipotle',             'chipotle',         'fast_food_restaurant',     'national'),
  ('chipotle mexican grill',        'Chipotle',             'chipotle',         'fast_food_restaurant',     'national'),
  ('panera',                        'Panera Bread',         'panera',           'cafe',                     'national'),
  ('panera bread',                  'Panera Bread',         'panera',           'cafe',                     'national'),
  ('dunkin''',                      'Dunkin''',             'dunkin',           'coffee_shop',              'national'),
  ('dunkin',                        'Dunkin''',             'dunkin',           'coffee_shop',              'national'),
  ('dunkin donuts',                 'Dunkin''',             'dunkin',           'coffee_shop',              'national'),
  ('sonic',                         'Sonic Drive-In',       'sonic',            'fast_food_restaurant',     'national'),
  ('sonic drive-in',                'Sonic Drive-In',       'sonic',            'fast_food_restaurant',     'national'),
  ('dairy queen',                   'Dairy Queen',          'dairy_queen',      'fast_food_restaurant',     'national'),
  ('dq',                            'Dairy Queen',          'dairy_queen',      'fast_food_restaurant',     'national'),
  ('arby''s',                       'Arby''s',              'arbys',            'fast_food_restaurant',     'national'),
  ('arbys',                         'Arby''s',              'arbys',            'fast_food_restaurant',     'national'),
  ('jack in the box',               'Jack in the Box',      'jack_in_the_box',  'fast_food_restaurant',     'national'),
  ('five guys',                     'Five Guys',            'five_guys',        'hamburger_restaurant',     'national'),
  ('in-n-out',                      'In-N-Out Burger',      'in_n_out',         'hamburger_restaurant',     'national'),
  ('in n out',                      'In-N-Out Burger',      'in_n_out',         'hamburger_restaurant',     'national'),
  ('whataburger',                   'Whataburger',          'whataburger',      'hamburger_restaurant',     'national'),
  ('raising cane''s',               'Raising Cane''s',      'raising_canes',    'fast_food_restaurant',     'national'),
  ('raising canes',                 'Raising Cane''s',      'raising_canes',    'fast_food_restaurant',     'national'),
  ('applebee''s',                   'Applebee''s',          'applebees',        'family_restaurant',        'national'),
  ('applebees',                     'Applebee''s',          'applebees',        'family_restaurant',        'national'),
  ('olive garden',                  'Olive Garden',         'olive_garden',     'italian_restaurant',       'national'),
  ('chili''s',                      'Chili''s',             'chilis',           'american_restaurant',      'national'),
  ('chilis',                        'Chili''s',             'chilis',           'american_restaurant',      'national'),
  ('outback',                       'Outback Steakhouse',   'outback',          'steak_house',              'national'),
  ('outback steakhouse',            'Outback Steakhouse',   'outback',          'steak_house',              'national'),
  ('texas roadhouse',               'Texas Roadhouse',      'texas_roadhouse',  'steak_house',              'national'),
  ('longhorn steakhouse',           'LongHorn Steakhouse',  'longhorn',         'steak_house',              'national'),
  ('cracker barrel',                'Cracker Barrel',       'cracker_barrel',   'family_restaurant',        'national'),
  ('ihop',                          'IHOP',                 'ihop',             'breakfast_restaurant',     'national'),
  ('denny''s',                      'Denny''s',             'dennys',           'family_restaurant',        'national'),
  ('dennys',                        'Denny''s',             'dennys',           'family_restaurant',        'national'),
  ('buffalo wild wings',            'Buffalo Wild Wings',   'buffalo_wild_wings','chicken_wings_restaurant','national'),
  ('bww',                           'Buffalo Wild Wings',   'buffalo_wild_wings','chicken_wings_restaurant','national'),
  ('7-eleven',                      '7-Eleven',             'seven_eleven',     'convenience_store',        'national'),
  ('7 eleven',                      '7-Eleven',             'seven_eleven',     'convenience_store',        'national'),
  ('711',                           '7-Eleven',             'seven_eleven',     'convenience_store',        'national'),
  ('circle k',                      'Circle K',             'circle_k',         'convenience_store',        'national'),
  ('wawa',                          'Wawa',                 'wawa',             'convenience_store',        'national'),
  ('sheetz',                        'Sheetz',               'sheetz',           'convenience_store',        'national'),
  ('buc-ee''s',                     'Buc-ee''s',            'buc_ees',          'convenience_store',        'national'),
  ('buc ees',                       'Buc-ee''s',            'buc_ees',          'convenience_store',        'national'),
  ('love''s',                       'Love''s Travel Stops', 'loves',            'truck_stop',               'national'),
  ('loves travel stop',             'Love''s Travel Stops', 'loves',            'truck_stop',               'national'),
  ('pilot',                         'Pilot Flying J',       'pilot',            'truck_stop',               'national'),
  ('flying j',                      'Pilot Flying J',       'pilot',            'truck_stop',               'national'),
  ('pilot flying j',                'Pilot Flying J',       'pilot',            'truck_stop',               'national'),
  ('shell',                         'Shell',                'shell',            'gas_station',              'national'),
  ('shell gas',                     'Shell',                'shell',            'gas_station',              'national'),
  ('exxon',                         'Exxon',                'exxon',            'gas_station',              'national'),
  ('exxonmobil',                    'Exxon',                'exxon',            'gas_station',              'national'),
  ('mobil',                         'Exxon',                'exxon',            'gas_station',              'national'),
  ('chevron',                       'Chevron',              'chevron',          'gas_station',              'national'),
  ('bp',                            'BP',                   'bp',               'gas_station',              'national'),
  ('british petroleum',             'BP',                   'bp',               'gas_station',              'national'),
  ('amoco',                         'BP',                   'bp',               'gas_station',              'national'),
  ('76 gas',                        '76',                   'phillips66',       'gas_station',              'national'),
  ('conoco',                        '76',                   'phillips66',       'gas_station',              'national'),
  ('phillips 66',                   '76',                   'phillips66',       'gas_station',              'national'),
  ('76 station',                    '76',                   'phillips66',       'gas_station',              'national'),
  ('speedway',                      'Speedway',             'speedway',         'gas_station',              'national'),
  ('autozone',                      'AutoZone',             'autozone',         'auto_parts_store',         'national'),
  ('o''reilly',                     'O''Reilly Auto Parts', 'oreilly',          'auto_parts_store',         'national'),
  ('o reilly',                      'O''Reilly Auto Parts', 'oreilly',          'auto_parts_store',         'national'),
  ('oreilly auto',                  'O''Reilly Auto Parts', 'oreilly',          'auto_parts_store',         'national'),
  ('advance auto',                  'Advance Auto Parts',   'advance_auto',     'auto_parts_store',         'national'),
  ('napa auto',                     'NAPA Auto Parts',      'napa',             'auto_parts_store',         'national'),
  ('napa auto parts',               'NAPA Auto Parts',      'napa',             'auto_parts_store',         'national'),
  ('jiffy lube',                    'Jiffy Lube',           'jiffy_lube',       'car_repair',               'national'),
  ('valvoline',                     'Valvoline',            'valvoline',        'car_repair',               'national'),
  ('valvoline instant oil',         'Valvoline',            'valvoline',        'car_repair',               'national'),
  ('midas',                         'Midas',                'midas',            'car_repair',               'national'),
  ('firestone',                     'Firestone',            'firestone',        'car_repair',               'national'),
  ('firestone complete auto',       'Firestone',            'firestone',        'car_repair',               'national'),
  ('discount tire',                 'Discount Tire',        'discount_tire',    'tire_shop',                'national'),
  ('america''s tire',               'Discount Tire',        'discount_tire',    'tire_shop',                'national'),
  ('enterprise',                    'Enterprise',           'enterprise',       'car_rental',               'national'),
  ('enterprise rent-a-car',         'Enterprise',           'enterprise',       'car_rental',               'national'),
  ('hertz',                         'Hertz',                'hertz',            'car_rental',               'national'),
  ('avis',                          'Avis',                 'avis',             'car_rental',               'national'),
  ('chase',                         'Chase Bank',           'chase',            'bank',                     'national'),
  ('chase bank',                    'Chase Bank',           'chase',            'bank',                     'national'),
  ('jpmorgan chase',                'Chase Bank',           'chase',            'bank',                     'national'),
  ('bank of america',               'Bank of America',      'bank_of_america',  'bank',                     'national'),
  ('boa',                           'Bank of America',      'bank_of_america',  'bank',                     'national'),
  ('wells fargo',                   'Wells Fargo',          'wells_fargo',      'bank',                     'national'),
  ('citibank',                      'Citibank',             'citibank',         'bank',                     'national'),
  ('citi',                          'Citibank',             'citibank',         'bank',                     'national'),
  ('u.s. bank',                     'U.S. Bank',            'us_bank',          'bank',                     'national'),
  ('us bank',                       'U.S. Bank',            'us_bank',          'bank',                     'national'),
  ('pnc',                           'PNC Bank',             'pnc',              'bank',                     'national'),
  ('pnc bank',                      'PNC Bank',             'pnc',              'bank',                     'national'),
  ('td bank',                       'TD Bank',              'td_bank',          'bank',                     'national'),
  ('capital one',                   'Capital One',          'capital_one',      'bank',                     'national'),
  ('regions',                       'Regions Bank',         'regions',          'bank',                     'national'),
  ('regions bank',                  'Regions Bank',         'regions',          'bank',                     'national'),
  ('marriott',                      'Marriott',             'marriott',         'hotel',                    'national'),
  ('courtyard',                     'Marriott',             'marriott',         'hotel',                    'national'),
  ('residence inn',                 'Marriott',             'marriott',         'hotel',                    'national'),
  ('springhill suites',             'Marriott',             'marriott',         'hotel',                    'national'),
  ('fairfield inn',                 'Marriott',             'marriott',         'hotel',                    'national'),
  ('towneplace suites',             'Marriott',             'marriott',         'hotel',                    'national'),
  ('ac hotel',                      'Marriott',             'marriott',         'hotel',                    'national'),
  ('ritz-carlton',                  'Marriott',             'marriott',         'hotel',                    'national'),
  ('jw marriott',                   'Marriott',             'marriott',         'hotel',                    'national'),
  ('autograph collection',          'Marriott',             'marriott',         'hotel',                    'national'),
  ('hilton',                        'Hilton',               'hilton',           'hotel',                    'national'),
  ('hampton inn',                   'Hilton',               'hilton',           'hotel',                    'national'),
  ('embassy suites',                'Hilton',               'hilton',           'hotel',                    'national'),
  ('homewood suites',               'Hilton',               'hilton',           'hotel',                    'national'),
  ('hilton garden inn',             'Hilton',               'hilton',           'hotel',                    'national'),
  ('doubletree',                    'Hilton',               'hilton',           'hotel',                    'national'),
  ('home2 suites',                  'Hilton',               'hilton',           'hotel',                    'national'),
  ('tru by hilton',                 'Hilton',               'hilton',           'hotel',                    'national'),
  ('waldorf astoria',               'Hilton',               'hilton',           'hotel',                    'national'),
  ('conrad',                        'Hilton',               'hilton',           'hotel',                    'national'),
  ('canopy',                        'Hilton',               'hilton',           'hotel',                    'national'),
  ('holiday inn',                   'IHG Hotels',           'ihg',              'hotel',                    'national'),
  ('holiday inn express',           'IHG Hotels',           'ihg',              'hotel',                    'national'),
  ('candlewood suites',             'IHG Hotels',           'ihg',              'hotel',                    'national'),
  ('staybridge suites',             'IHG Hotels',           'ihg',              'hotel',                    'national'),
  ('crowne plaza',                  'IHG Hotels',           'ihg',              'hotel',                    'national'),
  ('intercontinental',              'IHG Hotels',           'ihg',              'hotel',                    'national'),
  ('kimpton',                       'IHG Hotels',           'ihg',              'hotel',                    'national'),
  ('even hotels',                   'IHG Hotels',           'ihg',              'hotel',                    'national'),
  ('avid',                          'IHG Hotels',           'ihg',              'hotel',                    'national'),
  ('comfort inn',                   'Choice Hotels',        'choice',           'hotel',                    'national'),
  ('comfort suites',                'Choice Hotels',        'choice',           'hotel',                    'national'),
  ('quality inn',                   'Choice Hotels',        'choice',           'hotel',                    'national'),
  ('sleep inn',                     'Choice Hotels',        'choice',           'hotel',                    'national'),
  ('clarion',                       'Choice Hotels',        'choice',           'hotel',                    'national'),
  ('econo lodge',                   'Choice Hotels',        'choice',           'hotel',                    'national'),
  ('rodeway',                       'Choice Hotels',        'choice',           'hotel',                    'national'),
  ('mainstay',                      'Choice Hotels',        'choice',           'hotel',                    'national'),
  ('woodspring',                    'Choice Hotels',        'choice',           'hotel',                    'national'),
  ('wyndham',                       'Wyndham',              'wyndham',          'hotel',                    'national'),
  ('super 8',                       'Wyndham',              'wyndham',          'hotel',                    'national'),
  ('days inn',                      'Wyndham',              'wyndham',          'hotel',                    'national'),
  ('ramada',                        'Wyndham',              'wyndham',          'hotel',                    'national'),
  ('microtel',                      'Wyndham',              'wyndham',          'hotel',                    'national'),
  ('la quinta',                     'Wyndham',              'wyndham',          'hotel',                    'national'),
  ('baymont',                       'Wyndham',              'wyndham',          'hotel',                    'national'),
  ('howard johnson',                'Wyndham',              'wyndham',          'hotel',                    'national'),
  ('travelodge',                    'Wyndham',              'wyndham',          'hotel',                    'national'),
  ('best western',                  'Best Western',         'best_western',     'hotel',                    'national'),
  ('planet fitness',                'Planet Fitness',       'planet_fitness',   'fitness_center',           'national'),
  ('la fitness',                    'LA Fitness',           'la_fitness',       'fitness_center',           'national'),
  ('anytime fitness',               'Anytime Fitness',      'anytime_fitness',  'fitness_center',           'national'),
  ('orangetheory',                  'Orangetheory Fitness', 'orangetheory',     'fitness_center',           'national'),
  ('orange theory',                 'Orangetheory Fitness', 'orangetheory',     'fitness_center',           'national'),
  ('crunch fitness',                'Crunch Fitness',       'crunch',           'fitness_center',           'national'),
  ('crunch gym',                    'Crunch Fitness',       'crunch',           'fitness_center',           'national'),
  ('ymca',                          'YMCA',                 'ymca',             'fitness_center',           'national'),
  ('ymca of',                       'YMCA',                 'ymca',             'fitness_center',           'national'),
  ('ups store',                     'The UPS Store',        'ups_store',        'shipping_service',         'national'),
  ('the ups store',                 'The UPS Store',        'ups_store',        'shipping_service',         'national'),
  ('fedex',                         'FedEx',                'fedex',            'shipping_service',         'national'),
  ('fedex office',                  'FedEx',                'fedex',            'shipping_service',         'national'),
  ('fedex ship',                    'FedEx',                'fedex',            'shipping_service',         'national'),
  ('fedex print',                   'FedEx',                'fedex',            'shipping_service',         'national'),
  ('usps',                          'USPS',                 'usps',             'post_office',              'national'),
  ('us postal service',             'USPS',                 'usps',             'post_office',              'national'),
  ('united states postal',          'USPS',                 'usps',             'post_office',              'national'),
  ('h&r block',                     'H&R Block',            'h_and_r_block',    'accounting',               'national'),
  ('hr block',                      'H&R Block',            'h_and_r_block',    'accounting',               'national'),
  ('h & r block',                   'H&R Block',            'h_and_r_block',    'accounting',               'national'),
  ('jackson hewitt',                'Jackson Hewitt',       'jackson_hewitt',   'accounting',               'national'),
  ('state farm',                    'State Farm',           'state_farm',       'insurance_agency',         'national'),
  ('allstate',                      'Allstate',             'allstate',         'insurance_agency',         'national'),
  ('geico',                         'GEICO',                'geico',            'insurance_agency',         'national'),
  ('farmers insurance',             'Farmers Insurance',    'farmers',          'insurance_agency',         'national'),
  ('petsmart',                      'PetSmart',             'petsmart',         'pet_store',                'national'),
  ('petco',                         'Petco',                'petco',            'pet_store',                'national'),
  ('great clips',                   'Great Clips',          'great_clips',      'hair_salon',               'national'),
  ('supercuts',                     'Supercuts',            'supercuts',        'hair_salon',               'national'),
  ('massage envy',                  'Massage Envy',         'massage_envy',     'massage_spa',              'national'),
  ('european wax center',           'European Wax Center',  'european_wax',     'beauty_salon',             'national'),
  ('ulta',                          'Ulta Beauty',          'ulta',             'cosmetics_store',          'national'),
  ('ulta beauty',                   'Ulta Beauty',          'ulta',             'cosmetics_store',          'national'),
  ('sephora',                       'Sephora',              'sephora',          'cosmetics_store',          'national'),
  ('gamestop',                      'GameStop',             'gamestop',         'store',                    'national'),
  ('staples',                       'Staples',              'staples',          'store',                    'national'),
  ('office depot',                  'Office Depot',         'office_depot',     'store',                    'national'),
  ('officemax',                     'Office Depot',         'office_depot',     'store',                    'national'),
  ('party city',                    'Party City',           'party_city',       'store',                    'national'),
  ('hobby lobby',                   'Hobby Lobby',          'hobby_lobby',      'store',                    'national'),
  ('michaels',                      'Michaels',             'michaels',         'store',                    'national'),
  ('michael''s',                    'Michaels',             'michaels',         'store',                    'national'),
  ('joann',                         'JOANN',                'joann',            'store',                    'national'),
  ('jo-ann',                        'JOANN',                'joann',            'store',                    'national'),
  ('joann fabric',                  'JOANN',                'joann',            'store',                    'national'),
  ('barnes & noble',                'Barnes & Noble',       'barnes_noble',     'book_store',               'national'),
  ('barnes and noble',              'Barnes & Noble',       'barnes_noble',     'book_store',               'national'),
  ('dick''s sporting',              'Dick''s Sporting Goods','dicks',           'sporting_goods_store',     'national'),
  ('dicks sporting',                'Dick''s Sporting Goods','dicks',           'sporting_goods_store',     'national'),
  ('academy sports',                'Academy Sports',       'academy',          'sporting_goods_store',     'national'),
  ('academy sport',                 'Academy Sports',       'academy',          'sporting_goods_store',     'national'),
  ('rei',                           'REI',                  'rei',              'sporting_goods_store',     'national'),
  ('rei co-op',                     'REI',                  'rei',              'sporting_goods_store',     'national'),
  ('bass pro',                      'Bass Pro Shops',       'bass_pro',         'sporting_goods_store',     'national'),
  ('bass pro shops',                'Bass Pro Shops',       'bass_pro',         'sporting_goods_store',     'national'),
  ('cabela''s',                     'Bass Pro Shops',       'bass_pro',         'sporting_goods_store',     'national'),
  ('ace hardware',                  'Ace Hardware',         'ace_hardware',     'hardware_store',           'national'),
  ('tractor supply',                'Tractor Supply',       'tractor_supply',   'store',                    'national')
on conflict (name_pattern) do update
  set brand_id = excluded.brand_id,
      primary_type = excluded.primary_type,
      brand = excluded.brand;
